baseURL = 'https://nakasero.sirapollokaggwaschools.co.ug/'
locale = 'en-us'
title = 'Sir Apollo Kaggwa Primary School - Nakasero'
theme = "saks-theme"


[params]
logo = "/img/logo.png"
mainSchool = false
