baseURL = 'https://nakasero.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Sir Apollo Kaggwa Primary School - Nakasero'
theme = "saks-theme"


[params]
logo = "/img/logo.png"
mainSchool = false
defaultDescription = "Sir Apollo Kaggwa Primary School-Nakasero is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level."
    [params.school]
        hm_name = "BUYONDO FRANCIS"
        name = "nakasero"
        motto = 'Education with a Purpose'
        mission = 'To be a leading school in the provision of quality education'
        vision = 'The vision of Sir Apollo Kaggwa Primary School, Nakasero is to produce devoted learners in academics, moral education and life skills, leadership skills, creativity, and innovation, honest and humble, self-driven with a positive attitude towards quality work.'
        summary1 = 'Sir Apollo Kaggwa Primary School-Nakasero is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level. The school has two sections i.e pre-school and Primary school.'
        summary2 = 'At Sir Apollo Kaggwa Primary School, Nakasero, we are always learning through a holistic curriculum where individual talents are celebrated and nurtured. Working together as one team, in a caring, yet stimulating environment, we ensure that as an organization, excellence is the expectation. Our network of strong pastoral support fulfills the ambitions of students so that graduates go on to make a positive difference to the world in which they live.'
        hm = "Welcome to Sir Apollo Kaggwa Primary School Nakasero, a distinguished institution committed to providing holistic and high-quality primary education in Uganda. Guided by our inspiring motto, "We Persist to Excel," we are dedicated to nurturing learners who not only thrive academically but also grow into confident, disciplined, and responsible citizens."
    [params.carousel]
        two = "Offering a broad learning environment"
        three = "We train leaders by embracing smartness"
        four = "Offering the best learning skills to students"
        five = "Welcoming all types of students"
        six = "Interactive teachers that monitor pupils in all activities"
        